## This Python Notebook Is Used to Quickly Check the Performance of AWS and ML Functionality

In [4]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from PIL import Image
import json

format_data = []
img_data = Image.open("/Users/gavinfox/Documents/VS_Code/CHEF_test_img.jpg")
img_data = np.array(img_data)
print(img_data)

print(type(img_data[0][0]))
format_data.append(img_data)
image_tensor = tf.convert_to_tensor(format_data, dtype=tf.uint8)
#detector = hub.load("https://tfhub.dev/tensorflow/faster_rcnn/resnet50_v1_1024x1024/1")
detector = hub.load("/Users/gavinfox/Documents/VS_code/DREXEL_homework/CS375_Homework/Final_project_code/ML_models/faster_rcnn_resnet50_v1_1024x1024_1")
detector_output = detector(image_tensor)

print(detector_output)
f = open("example_output.txt","w")
f.write(str(detector_output))
f.close()

[[[188 205 233]
  [188 205 233]
  [187 204 232]
  ...
  [193 208 239]
  [193 208 239]
  [193 208 239]]

 [[188 205 233]
  [187 204 232]
  [187 204 232]
  ...
  [193 208 239]
  [193 208 239]
  [193 208 239]]

 [[187 204 232]
  [187 204 232]
  [186 203 231]
  ...
  [193 208 239]
  [193 208 239]
  [193 208 239]]

 ...

 [[169 192 226]
  [169 192 226]
  [168 191 225]
  ...
  [171 195 233]
  [169 193 231]
  [167 191 229]]

 [[169 192 226]
  [169 192 226]
  [168 191 225]
  ...
  [172 196 234]
  [171 195 233]
  [169 193 231]]

 [[169 192 226]
  [169 192 226]
  [168 191 225]
  ...
  [173 197 235]
  [171 195 233]
  [169 193 231]]]
<class 'numpy.ndarray'>
{'raw_detection_scores': <tf.Tensor: shape=(1, 300, 91), dtype=float32, numpy=
array([[[9.96484637e-01, 2.16894987e-05, 1.10281849e-06, ...,
         4.99258203e-06, 3.92737221e-08, 3.97305513e-07],
        [2.22830534e-01, 1.20005134e-04, 3.92240418e-06, ...,
         1.42505014e-04, 4.98296004e-07, 7.72371277e-06],
        [8.62073243e-01, 1.

In [16]:
!python model-predict.py FOOD /Users/gavinfox/Documents/VS_code/DREXEL_homework/CS375_Homework/Final_project_code/test_img.jpg

Printing Arguments...
model-predict.py LANDMARKS /Users/gavinfox/Documents/VS_code/DREXEL_homework/CS375_Homework/Final_project_code/test_img.jpg
landmark NA
2021-09-01 19:31:42.697469: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-01 19:31:43.733086: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
Model Loaded
Traceback (most recent call last):
  File "model-predict.py", line 189, in <module>
    predict()
  File "model-predict.py", line 135, in predict
    detector_output = detector(image)
TypeError: 'AutoTrackable' object is not callable


In [24]:
!python aws.py test123 test_img.jpg

aws.py test123 test_img.jpg
AWS CONNECTED
{'ResponseMetadata': {'RequestId': 'FRVBYBN7A8AN9SX0', 'HostId': '8RDLo522vlEAa1k4qq5FLR0m759L2WjhC0aFyeytb4WmldW4Rah+iV/khXjomvomgpgrJyF6RX4=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': '8RDLo522vlEAa1k4qq5FLR0m759L2WjhC0aFyeytb4WmldW4Rah+iV/khXjomvomgpgrJyF6RX4=', 'x-amz-request-id': 'FRVBYBN7A8AN9SX0', 'date': 'Thu, 02 Sep 2021 04:53:23 GMT', 'x-amz-bucket-region': 'us-east-1', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'cs375ml', 'Prefix': '', 'Delimiter': '/', 'MaxKeys': 1000, 'CommonPrefixes': [{'Prefix': 'test123/'}], 'EncodingType': 'url', 'KeyCount': 1}
Filename: /Users/gavinfox/Documents/VS_code/DREXEL_homework/CS375_Homework/Final_project_code/temp_img/test_img.jpg
Folder: test123/test_img
New_file: test_img.jpg
test123/test_img/test_img.jpg
